version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    ports:
    - "63000:5432"
    volumes:
    - ".docker/postgresdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres